name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: compile with maven
      run: mvn clean compile my-app/pom.xml

    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml

