name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B clean package -f ./my-app/
     
    - name: tree
      run: tree
      
    - name: build docker image
      run: docker build -t maayanmi/artifact ./my-app/
      
    - name: login dockerhub
      run: docker login -u maayanmi -p dckr_pat_Ss2xH7o8NeJ4zrgENxZH2X3VpWY
      
    - name: push to dockerhub
      run: docker push maayanmi/artifact
      
    - name: pull from dockerhub
      run: docker run --name artifact -t maayanmi/artifact

